# Generated by Django 2.2.7 on 2020-11-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
